server:
  port: 5002

spring:
  application:
    name: HOTEL-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/hotelservice
    username: postgres
    password: 25239223
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect


  config:
    import: configserver:http://localhost:5555
