server:
  port: 5003

spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://nimeshrajani25:25239223@cluster0.w1v78.mongodb.net/Cluster0?retryWrites=true&w=majority&appName=Cluster0

  config:
    import: configserver:http://localhost:5555