server:
  port: 5003

spring:
  data:
    mongodb:
      uri: mongodb+srv://nimeshrajani25:25239223@cluster0.w1v78.mongodb.net/Cluster0?retryWrites=true&w=majority&appName=Cluster0

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:5050/eureka/